services:
  - type: web
    name: nine-days
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: redirect
        source: /*
        destination: /index.html